version: "3.8"

services:
  api:
    container_name: movies-api
    build: .
    command: sh -c "npx tsc && node dist/index"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
    env_file:
      - .env
  postgres:
    container_name: movies-postgres
    image: postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5435:5432"
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - movies-postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  movies-postgres:
